name: project_food
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"




dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Firebase Setup
  firebase_core: ^2.6.1
  firebase_database: ^10.0.13
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.10 
  firebase_storage: ^11.0.16

  #Flutter Bar Bar
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  shimmer: ^2.0.0

  #Pick file
  file_picker: ^5.2.6
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - images/logo.png